/* Тексты, тайминги и лимиты раздела.

   Часть раздела «Квант» — вторая вкладка «Пространство вариантов».
   Модуль изолирован: кроме этой папки и двух строк в app.js он ничего
   в Ежедневнике не трогает.

   Здесь правятся формулировки экранов и время кулдауна. */

export const CONFIG = {
    doors: {
        min: 2,
        max: 7,
        defaultCount: 7
    },
    timing: {
        quantumWindowSeconds: 33.3,
        jumpCooldownMs: (3 * 60 * 60 * 1000) + (33 * 60 * 1000), // 3 часа 33 минуты
        opportunityWindowMs: (88 * 60 + 8) * 1000, // 88 минут 8 секунд
        snoozeDurationMs: 10 * 60 * 1000, // 10 минут
        maxSnoozeCount: 3
    },
    dailyWindow: {
        startHour: 6,
        endHour: 21
    },
    // Словарь мультиязычности
    translations: {
        ru: {
            btnCloseSection: "Закрыть раздел",
            audioAdd: "Добавить аудио",
            audioRecord: "Записать",
            audioStopRec: "Остановить",
            audioPickFile: "Файл",
            audioPlay: "Прослушать",
            audioPause: "Пауза",
            audioRemove: "Удалить",
            audioRecording: "Идёт запись…",
            audioNoMic: "Нет доступа к микрофону",
            audioNoRecorder: "Запись с микрофона в этом браузере недоступна",
            audioMissing: "Аудиофайл недоступен, доступен текстовый режим",
            audioPlayAria: "Включить аудио двери",
            audioStopAria: "Остановить аудио двери",
            audioNoneAria: "В этой двери нет записи",
            akashaDone: "ЗАПИСАНО",
            recElapsed: "Идёт запись",
            photoAdd: "Фото",
            photoLimitReached: "Больше трёх фотографий не поместится",
            photoRemove: "Убрать фотографию",
            doorReady: "Готово",
            doorTitlePhoto: "Фото",
            doorTitleAudio: "Запись",
            doorTitleEmpty: "Без названия",
            chronicles24h: "За последние 24 часа",
            chroniclesAll: "За всё время",
            chroniclesNoneDay: "За сутки переходов не было",
            chroniclesTimesOne: "открытие",
            chroniclesTimesFew: "открытия",
            chroniclesTimesMany: "открытий",
            tabMoments: "Моменты",
            tabSpace: "Пространство вариантов",
            metaverseTitle: "Моя метавселенная",
            title1: "Пространство вариантов",
            btnStart: "Войти в суперпозицию",
            btnSettings: "Изменить варианты реальностей",
            multiverse: "Мультивселенная",
            setupTitle: "Настройка Реальностей",
            setupSub: "Выбери от 2 до 7 дверей и опиши намерения:",
            doorsCount: "Количество дверей:",
            btnSave: "Сохранить и войти",
            btnCancel: "Отмена",
            doorPlaceholder: "Намерение реальности...",
            screen2Instruction: "Квантовое окно открыто 33,3 секунды.\nВойди в свою новую реальность сейчас.",
            screen3MainTitle: "Настройка реальности",
            screen3Subtitle: "Свершилось. Выход из суперпозиции завершен. Я наблюдаю новую реальность, не зная, кто, как и где её воплотит.",
            screen3SpeedTitle: "Для завершения перехода и полного перемещения в новую реальность зафиксируй это состояние. Выбери скорость:",
            speedOption1Btn: "Быстрый переход (в потоке дня)",
            speedOption1Text: "Закрой глаза, посчитай до трёх. Сделай глубокий вдох, всем телом вдыхая в себя эту новую реальность, и на выдохе медленно открывай глаза.",
            speedOption2Btn: "Глубокое погружение (есть время)",
            speedBadge: "(Рекомендуем)",
            speedOption2Text: "Закрой глаза и дыши ровно. Максимально подробно проживи с закрытыми глазами всё то, чего ты хочешь. Прочувствуй окружение, людей, дотрагивайся до деталей. Проживи, продыши и сконцентрируйся в своём теле: где и что сейчас происходит.",
            screen3Btn: "Закрой глаза",
            screen4Top: "Пространство уже само собой поменялось. Наблюдай и фиксируй события сегодняшнего дня, особенно необычные, подтверждающие твой выбор.",
            screen4Title: "Дневник Наблюдателя",
            screen4Subtitle: "Зафиксируй: что ты прожил в этот момент? В какой части тела откликнулась твоя новая реальность? Опиши в деталях свои ощущения и эмоции от того, что твой выбор воплотился в жизнь прямо сейчас.",
            screen4Placeholder: "В теле сейчас я чувствую... [где: в груди, животе, плечах, горле, голове]...\nОщущаю физически: [тепло, жар, мурашки, расслабление, холод, трепет, расширение, сжатие, легкость, покалывание]...\nМои эмоции: [радость, спокойствие, волнение, страх, восторг, благодарность, уверенность, предвкушение, эйфория, тишина]...",
            screen4Btn: "Активировать в Хрониках Акаши",
            screen5Title: "Активации в Хрониках Акаши",
            screen5Subtitle: "Твоя новая реальность зафиксирована в ткани мироздания. Записи квантовых переходов успешно обновлены.",
            btnEditFromS5: "Настройки дверей",
            btnSnooze: "Отложить на 10 минут",
            timerPrefix: "До возможного следующего прыжка: ",
            emptyTrace: "Проявлено в тишине",
            doorMinAlert: "Пожалуйста, заполните минимум {min} двери!",
            snoozeAlertLimit: "Лимит откладываний исчерпан (максимум 3 раза).",
            snoozeAlertOk: "Окно отложено на 10 минут.",
            windowOpen: "Квантовое окно открыто!",
            noRecords: "Записей пока нет.",
            akashiAct: "Активация ветки реальности:",
            akashiTrace: "КВАНТОВЫЙ СЛЕД:",
            modalTitle: "Окно возможностей открыто",
            modalSubtitle: "Для того, чтобы воспользоваться окном возможностей. У вас есть 88 минут и 8 секунд.",
            modalElapsedPrefix: "прошло ",
            modalWarning: "Если пропустить окно, цикл сбросится и начнется новое ожидание.",
            modalBtnStart: "Войти в суперпозицию",
            modalBtnLater: "Позже (Оставить в дашборде)"
        },
        en: {
            btnCloseSection: "Close section",
            audioAdd: "Add audio",
            audioRecord: "Record",
            audioStopRec: "Stop",
            audioPickFile: "File",
            audioPlay: "Listen",
            audioPause: "Pause",
            audioRemove: "Remove",
            audioRecording: "Recording…",
            audioNoMic: "No access to the microphone",
            audioNoRecorder: "Recording is not available in this browser",
            audioMissing: "Audio file unavailable, text mode only",
            audioPlayAria: "Play the door audio",
            audioStopAria: "Stop the door audio",
            audioNoneAria: "This door has no recording",
            akashaDone: "RECORDED",
            recElapsed: "Recording",
            photoAdd: "Photos",
            photoLimitReached: "Three photos is the limit",
            photoRemove: "Remove photo",
            doorReady: "Ready",
            doorTitlePhoto: "Photo",
            doorTitleAudio: "Recording",
            doorTitleEmpty: "Untitled",
            chronicles24h: "Last 24 hours",
            chroniclesAll: "All time",
            chroniclesNoneDay: "No transitions in the last 24 hours",
            chroniclesTimesOne: "opening",
            chroniclesTimesFew: "openings",
            chroniclesTimesMany: "openings",
            tabMoments: "Moments",
            tabSpace: "Space of Variations",
            metaverseTitle: "My Metaverse",
            title1: "Space of Variations",
            btnStart: "Enter Superposition",
            btnSettings: "Change Reality Variants",
            multiverse: "Multiverse",
            setupTitle: "Reality Setup",
            setupSub: "Choose from 2 to 7 doors and describe your intentions:",
            doorsCount: "Number of doors:",
            btnSave: "Save and Enter",
            btnCancel: "Cancel",
            doorPlaceholder: "Reality intention...",
            screen2Instruction: "Quantum window is open for 33.3 seconds.\nEnter your new reality now.",
            screen3MainTitle: "Reality Setup",
            screen3Subtitle: "It is done. Exit from superposition complete. I observe a new reality, not knowing who, how, or where will bring it to life.",
            screen3SpeedTitle: "To complete the transition and fully move into the new reality, fix this state. Choose speed:",
            speedOption1Btn: "Fast transition (in flow)",
            speedOption1Text: "Close your eyes, count to three. Take a deep breath, inhaling this new reality with your whole body, and slowly open your eyes on the exhale.",
            speedOption2Btn: "Deep immersion (time available)",
            speedBadge: "(Recommended)",
            speedOption2Text: "Close your eyes and breathe evenly. Live through everything you desire with your eyes closed in maximum detail. Feel the surroundings, people, touch details. Live it, breathe it, and concentrate in your body: where and what is happening right now.",
            screen3Btn: "Close your eyes",
            screen4Top: "Space has already changed by itself. Observe and record today's events, especially unusual ones, confirming your choice.",
            screen4Title: "Observer's Diary",
            screen4Subtitle: "Record: what did you experience in this moment? Where in your body did your new reality resonate? Describe in detail your feelings and emotions from the fact that your choice has materialized in life right now.",
            screen4Placeholder: "In my body right now I feel... [where: chest, stomach, shoulders, throat, head]...\nI feel physically: [warmth, heat, goosebumps, relaxation, cold, thrill, expansion, contraction, lightness, tingling]...\nMy emotions: [joy, calm, excitement, fear, delight, gratitude, confidence, anticipation, euphoria, silence]...",
            screen4Btn: "Activate in Akashic Records",
            screen5Title: "Activations in Akashic Records",
            screen5Subtitle: "Your new reality is fixed in the fabric of the universe. Quantum jump records successfully updated.",
            btnEditFromS5: "Door Settings",
            btnSnooze: "Snooze for 10 mins",
            timerPrefix: "Until the next possible jump: ",
            emptyTrace: "Manifested in silence",
            doorMinAlert: "Please fill in at least {min} doors!",
            snoozeAlertLimit: "Snooze limit reached (max 3 times).",
            snoozeAlertOk: "Window snoozed for 10 minutes.",
            windowOpen: "Quantum window is open!",
            noRecords: "No records yet.",
            akashiAct: "Reality branch activation:",
            akashiTrace: "QUANTUM TRACE:",
            modalTitle: "Opportunity Window Open",
            modalSubtitle: "To take advantage of the opportunity window. You have 88 minutes and 8 seconds.",
            modalElapsedPrefix: "elapsed ",
            modalWarning: "If you miss the window, the cycle will reset and a new wait will begin.",
            modalBtnStart: "Enter Superposition",
            modalBtnLater: "Later (Keep in Dashboard)"
        },
        uk: {
            btnCloseSection: "Закрити розділ",
            audioAdd: "Додати аудіо",
            audioRecord: "Записати",
            audioStopRec: "Зупинити",
            audioPickFile: "Файл",
            audioPlay: "Прослухати",
            audioPause: "Пауза",
            audioRemove: "Видалити",
            audioRecording: "Триває запис…",
            audioNoMic: "Немає доступу до мікрофона",
            audioNoRecorder: "Запис з мікрофона в цьому браузері недоступний",
            audioMissing: "Аудіофайл недоступний, доступний текстовий режим",
            audioPlayAria: "Увімкнути аудіо дверей",
            audioStopAria: "Зупинити аудіо дверей",
            audioNoneAria: "У цих дверях немає запису",
            akashaDone: "ЗАПИСАНО",
            recElapsed: "Триває запис",
            photoAdd: "Фото",
            photoLimitReached: "Більше трьох фотографій не вміститься",
            photoRemove: "Прибрати фотографію",
            doorReady: "Готово",
            doorTitlePhoto: "Фото",
            doorTitleAudio: "Запис",
            doorTitleEmpty: "Без назви",
            chronicles24h: "За останні 24 години",
            chroniclesAll: "За весь час",
            chroniclesNoneDay: "За добу переходів не було",
            chroniclesTimesOne: "відкриття",
            chroniclesTimesFew: "відкриття",
            chroniclesTimesMany: "відкриттів",
            tabMoments: "Моменти",
            tabSpace: "Простір варіантів",
            metaverseTitle: "Мій метавсесвіт",
            title1: "Простір варіантів",
            btnStart: "Увійти в суперпозицію",
            btnSettings: "Змінити варіанти реальностей",
            multiverse: "Мультивсесвіт",
            setupTitle: "Налаштування Реальностей",
            setupSub: "Обери від 2 до 7 дверей і опиши наміри:",
            doorsCount: "Кількість дверей:",
            btnSave: "Зберегти та увійти",
            btnCancel: "Скасувати",
            doorPlaceholder: "Намір реальності...",
            screen2Instruction: "Квантове вікно відкрито 33,3 секунди.\nУвійди у свою нову реальність зараз.",
            screen3MainTitle: "Налаштування реальності",
            screen3Subtitle: "Здійснилося. Вихід із суперпозиції завершено. Я спостерігаю нову реальність, не знаючи, хто, як і де її втілить.",
            screen3SpeedTitle: "Для завершення переходу та повного переміщення в нову реальність зафіксуй цей стан. Обери швидкість:",
            speedOption1Btn: "Швидкий перехід (у потоці дня)",
            speedOption1Text: "Заплющ очі, порахуй до трьох. Зроби глибокий вдих, усім тілом вдихаючи в себе цю нову реальність, і на видиху повільно розплющуй очі.",
            speedOption2Btn: "Глибоке занурення (є час)",
            speedBadge: "(Рекомендуємо)",
            speedOption2Text: "Заплющ очі та дихай рівно. Максимально детально проживи із заплющеними очима все те, чого ти прагнеш. Відчуй оточення, людей, торкайся деталей. Проживи, продихай і сконцентруйся у своєму тілі: де і що зараз відбувається.",
            screen3Btn: "Заплющ очі",
            screen4Top: "Простір вже сам собою змінився. Спостерігай і фіксуй події сьогоднішнього дня, особливо незвичні, що підтверджують твій вибір.",
            screen4Title: "Щоденник Спостерігача",
            screen4Subtitle: "Зафіксуй: що ти прожив у цей момент? В якій частині тіла відгукнулася твоя нова реальність? Опиши в деталях свої відчуття та емоції від того, що твій вибір втілився в житті прямо зараз.",
            screen4Placeholder: "У тілі зараз я відчуваю... [де: у грудях, животі, плечах, горлі, голові]...\nВідчуваю фізично: [тепло, жар, мурашки, розслаблення, холод, трепет, розширення, стиснення, легкість, поколювання]...\nМої емоції: [радість, спокій, хвилювання, страх, захват, вдячність, впевненість, передчуття, ейфорія, тиша]...",
            screen4Btn: "Активувати в Хроніках Акаші",
            screen5Title: "Активації в Хроніках Акаші",
            screen5Subtitle: "Твоя нова реальність зафіксована в тканині світобудови. Записи квантових переходів успішно оновлені.",
            btnEditFromS5: "Налаштування дверей",
            btnSnooze: "Відкласти на 10 хвилин",
            timerPrefix: "До можливого наступного стрибка: ",
            emptyTrace: "Проявлено в тиші",
            doorMinAlert: "Будь ласка, заповніть мінімум {min} двері!",
            snoozeAlertLimit: "Ліміт відкладень вичерпано (максимум 3 рази).",
            snoozeAlertOk: "Вікно відкладено на 10 хвилин.",
            windowOpen: "Квантове вікно відкрито!",
            noRecords: "Записів поки немає.",
            akashiAct: "Активація гілки реальності:",
            akashiTrace: "КВАНТОВИЙ СЛІД:",
            modalTitle: "Вікно можливостей відкрито",
            modalSubtitle: "Для того, щоб скористатися вікном можливостей. У вас є 88 хвилин і 8 секунд.",
            modalElapsedPrefix: "минуло ",
            modalWarning: "Якщо пропустити вікно, цикл скинеться і розпочнеться нове очікування.",
            modalBtnStart: "Увійти в суперпозицію",
            modalBtnLater: "Пізніше (Залишити в дашборді)"
        }
    }
};
